### ISSUE TITLE
Field [foo] is defined twice in [bar] errors

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/es-whosonfirst-schema#13]
Wuh...

```
wof-es-index-files --host=1.2.3.4 --port 9200 --index=spelunker ./874411075.geojson --verbose
DEBUG:root:processing sg:province: PA
DEBUG:root:processing sg:tags: academic
DEBUG:root:processing sg:tags: school
DEBUG:root:processing geom:bbox: -75.794172,40.50556,-75.775505,40.516952
DEBUG:root:processing geom:longitude: -75.785614
DEBUG:root:processing counts:languages_total: 0
DEBUG:root:processing counts:names_total: 0
DEBUG:root:processing sg:website: www.kutztownsbdc.org
DEBUG:root:processing wof:concordances_sources: sg:id
DEBUG:root:processing wof:country: US
DEBUG:root:processing category: Education
DEBUG:root:processing type: Public Place
DEBUG:root:processing subcategory: College
DEBUG:root:processing sg:categories: sg/public_place/education
DEBUG:root:processing sg:categories: public_place/education/college
DEBUG:root:processing sg:address: 15200 Kutztown Rd
DEBUG:root:processing sg:phone: +1 610 683 4000
DEBUG:root:processing region_id: 85688481
DEBUG:root:processing country_id: 85633793
DEBUG:root:processing campus_id: 874411075
DEBUG:root:processing neighbourhood_id: 85827973
DEBUG:root:processing county_id: 102080991
DEBUG:root:processing counts:languages_official: 0
DEBUG:root:processing mps:longitude: -75.788583
DEBUG:root:processing geom:type: Polygon
DEBUG:root:processing mps:latitude: 40.51186
DEBUG:root:processing iso:country: US
DEBUG:root:processing lbl:latitude: 40.51186
DEBUG:root:processing wof:geomhash: 9f657ee64ba039798e7681bed8d2e08d
DEBUG:root:processing wof:name: Kutztown University of PA
DEBUG:root:processing counts:names_variant: 0
DEBUG:root:processing src:geom: simplegeo
DEBUG:root:processing wof:supersedes: 101719267
DEBUG:root:processing wof:supersedes: 621997697
DEBUG:root:processing counts:names_colloquial: 0
DEBUG:root:processing wof:id: 874411075
DEBUG:root:processing lbl:longitude: -75.788583
DEBUG:root:processing counts:names_prefered: 0
DEBUG:root:processing wof:tags: academic
DEBUG:root:processing wof:tags: school
DEBUG:root:processing geom:area: 0.000102
DEBUG:root:processing edtf:inception: uuuu
DEBUG:root:processing sg:owner: simplegeo
DEBUG:root:processing sg:postcode: 19530
DEBUG:root:processing geom:latitude: 40.511248
DEBUG:root:processing wof:placetype_id: 102312331
DEBUG:root:processing sg:city: Kutztown
DEBUG:root:processing edtf:cessation: uuuu
DEBUG:root:processing counts:concordances_total: 1
DEBUG:root:processing counts:languages_spoken: 0
DEBUG:root:processing wof:belongsto: 85688481
DEBUG:root:processing wof:belongsto: 85633793
DEBUG:root:processing wof:belongsto: 85827973
DEBUG:root:processing wof:belongsto: 102080991
DEBUG:root:processing wof:placetype: campus
DEBUG:root:processing counts:names_languages: 0
DEBUG:root:processing wof:lastmodified: 1471552675
DEBUG:root:processing sg:id: SG_6tmpRVg8TcOL14L7dUsxeJ_40.510300_-75.783579@1294186258
DEBUG:root:processing wof:parent_id: 85827973
DEBUG:urllib3.util.retry:Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
INFO:urllib3.connectionpool:Starting new HTTP connection (1): 1.2.3.4
DEBUG:urllib3.connectionpool:"PUT /spelunker/campus/874411075 HTTP/1.1" 400 285
WARNING:elasticsearch:PUT /spelunker/campus/874411075 [status:400 request:0.007s]
DEBUG:elasticsearch:> {"sg:province": "PA", "sg:tags": ["academic", "school"], "geom:bbox": "-75.794172,40.50556,-75.775505,40.516952", "geom:longitude": -75.785614, "counts:languages_total": "0", "counts:names_total": "0", "sg:website": "www.kutztownsbdc.org", "wof:concordances_sources": ["sg:id"], "mz:categories": [], "wof:country": "US", "sg:classifiers": [{"category": "Education", "type": "Public Place", "subcategory": "College"}], "sg:categories": ["sg/public_place/education", "public_place/education/college"], "sg:address": "15200 Kutztown Rd", "sg:phone": "+1 610 683 4000", "wof:hierarchy": [{"region_id": 85688481, "country_id": 85633793, "campus_id": "874411075", "neighbourhood_id": 85827973, "county_id": 102080991}], "counts:languages_official": "0", "mps:longitude": -75.788583, "geom:type": "Polygon", "mps:latitude": 40.51186, "iso:country": "US", "lbl:latitude": 40.51186, "wof:geomhash": "9f657ee64ba039798e7681bed8d2e08d", "wof:name": "Kutztown University of PA", "counts:names_variant": "0", "src:geom": "simplegeo", "wof:supersedes": [101719267, 621997697], "counts:names_colloquial": "0", "wof:id": 874411075, "wof:breaches": [], "lbl:longitude": -75.788583, "counts:names_prefered": "0", "wof:tags": ["academic", "school"], "geom:area": 0.000102, "wof:placetype_names": [], "edtf:inception": "uuuu", "sg:owner": "simplegeo", "sg:postcode": "19530", "geom:latitude": 40.511248, "wof:placetype_id": 102312331, "sg:city": "Kutztown", "edtf:cessation": "uuuu", "counts:concordances_total": "1", "counts:languages_spoken": "0", "wof:categories": [], "wof:belongsto": [85688481, 85633793, 85827973, 102080991], "wof:placetype": "campus", "counts:names_languages": "0", "wof:lastmodified": 1471552675, "wof:superseded_by": [], "wof:concordances": {"sg:id": "SG_6tmpRVg8TcOL14L7dUsxeJ_40.510300_-75.783579@1294186258"}, "wof:parent_id": "85827973"}
DEBUG:elasticsearch:< {"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[elasticsearch-whosonfirst-a.localdomain][1.2.3.4:9300][indices:data/write/index]"}],"type":"illegal_argument_exception","reason":"Field [sg:classifiers.category] is defined twice in [campus]"},"status":400}
Traceback (most recent call last):
  File "/usr/local/bin/wof-es-index-files", line 5, in <module>
    pkg_resources.run_script('mapzen.whosonfirst.search==0.184-', 'wof-es-index-files')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/mapzen.whosonfirst.search-0.184_-py2.7.egg/EGG-INFO/scripts/wof-es-index-files", line 33, in <module>
    
  File "build/bdist.linux-x86_64/egg/mapzen/whosonfirst/search/__init__.py", line 455, in index_file
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 69, in _wrapped
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 279, in index
  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 329, in perform_request
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 108, in _raise_error
elasticsearch.exceptions.RequestError: TransportError(400, u'illegal_argument_exception', u'[elasticsearch-whosonfirst-a.localdomain][1.2.3.4:9300][indices:data/write/index]')
```

Possibly related: issue #11 ?

**Comment by thisisaaronland** [comment]
Possible WTF:
- https://discuss.elastic.co/t/upgrade-from-2-1-1-to-2-2-0-field--id-is-defined-twice-elasticsearch/40845
- https://github.com/elastic/elasticsearch-rails/issues/563

**Comment by thisisaaronland** [comment]
This does not appear to be a "doctype" related problem. I can reproduce it when every record shares the same doctype (rather than `wof['placetype']`)

**Comment by thisisaaronland** [comment]
This does not happen if I remove:

```
                "sg:classifiers.category": {
                    "type" : "string",
                    "index" : "not_analyzed"
                },
                "sg:classifiers.subcategory": {
                    "type" : "string",
                    "index" : "not_analyzed"
                },
                "sg:classifiers.type": {
                    "type" : "string",
                    "index" : "not_analyzed"
                },
```

From the schema. See also issue #11

**Comment by thisisaaronland** [comment]
It is possible that I've just _always_ been indexing `sg:categories` stuff badly. It _appears_ that assuming ES will decompose things in dot notation to nested structs is a mistake. No idea why it worked under 1.7

Leaving this ticket open pending a re-indexing...

**Comment by thisisaaronland** [comment]
Indexing was successful.
