### ISSUE TITLE
OMGWTF mapping nested things

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/es-whosonfirst-schema#6]
Figure out what syntax is required to index stuff like this...

```
                "sg:classifiers.category": {
                    "type" : "string",
                    "index" : "not_analyzed"
                },
                "sg:classifiers.subcategory": {
                    "type" : "string",
                    "index" : "not_analyzed"
                },
                "sg:classifiers.type": {
                    "type" : "string",
                    "index" : "not_analyzed"
                },
                "sg:tags.type": {
                    "type" : "string",
                    "index" : "not_analyzed",
                    "copy_to": "tags_all"
                },
```

**Comment by thisisaaronland** [comment]
Just recording the latest error...

```
workhorse-1:/usr/local/mapzen/acope/whosonfirst-data-utils> sh ./es-refeed.sh
Thu Oct 13 15:06:54 UTC 2016
index whosonfirst-data
ERROR:root:failed to parse 'eng_p', because need more than 1 value to unpack
ERROR:root:failed to parse 'eng_p', because need more than 1 value to unpack
Traceback (most recent call last):
  File "/usr/local/bin/wof-es-index", line 5, in <module>
    pkg_resources.run_script('mapzen.whosonfirst.search==0.183-', 'wof-es-index')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/mapzen.whosonfirst.search-0.183_-py2.7.egg/EGG-INFO/scripts/wof-es-index", line 40, in <module>

  File "build/bdist.linux-x86_64/egg/mapzen/whosonfirst/search/__init__.py", line 459, in index_files
  File "build/bdist.linux-x86_64/egg/elasticsearch/helpers/__init__.py", line 188, in bulk
  File "build/bdist.linux-x86_64/egg/elasticsearch/helpers/__init__.py", line 160, in streaming_bulk
  File "build/bdist.linux-x86_64/egg/elasticsearch/helpers/__init__.py", line 132, in _process_bulk_chunk
elasticsearch.helpers.BulkIndexError: (u'1 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'campus', u'_id': u'874411075', u'error': {u'reason': u'obje\
ct mapping for [sg:categories] tried to parse field [null] as object, but found a concrete value', u'type': u'mapper_parsing_exception'}, u'_index': u'whosonfirst_20161013'}}\
])
Command exited with non-zero status 1
775.03user 23.02system 20:26.18elapsed 65%CPU (0avgtext+0avgdata 686984maxresident)k
9112872inputs+0outputs (7major+1057707minor)pagefaults 0swaps
/usr/local/mapzen/acope/whosonfirst-data-utils
Thu Oct 13 15:27:20 UTC 2016
```

**Comment by thisisaaronland** [comment]
I don't understand why this is still happening (because the schema should be trapping it) but it is...

```
Thu Oct 13 19:22:18 UTC 2016
index whosonfirst-data
ERROR:root:failed to parse 'eng_p', because need more than 1 value to unpack
ERROR:root:failed to parse 'eng_p', because need more than 1 value to unpack
Traceback (most recent call last):
  File "/usr/local/bin/wof-es-index", line 5, in <module>
    pkg_resources.run_script('mapzen.whosonfirst.search==0.183-', 'wof-es-index')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/mapzen.whosonfirst.search-0.183_-py2.7.egg/EGG-INFO/scripts/wof-es-index", line 40, in <module>

  File "build/bdist.linux-x86_64/egg/mapzen/whosonfirst/search/__init__.py", line 459, in index_files
  File "build/bdist.linux-x86_64/egg/elasticsearch/helpers/__init__.py", line 188, in bulk
  File "build/bdist.linux-x86_64/egg/elasticsearch/helpers/__init__.py", line 160, in streaming_bulk
  File "build/bdist.linux-x86_64/egg/elasticsearch/helpers/__init__.py", line 132, in _process_bulk_chunk
elasticsearch.helpers.BulkIndexError: (u'29 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'macrohood', u'_id': u'890537225', u'error': {u'caused_by':\
 {u'reason': u'Invalid format: "2015/03/31" is malformed at "/03/31"', u'type': u'illegal_argument_exception'}, u'reason': u'failed to parse [fsgov:ajo_pvm]',
```

**Comment by thisisaaronland** [comment]
Just fixed by ignoring `fsgov:ajo_pvm` in python-land for now...
